README.md
index.js
package.json
test/index.js

* Allows up to 10 messages to be requested from SQS at a time
* Uses `async.each` to process multiple messages.
* Removes the `waitTime` parameter. The consumer now waits until the current batch of messages has been processed before requesting a new batch. This applies to single messages as well. This provides some back pressure on the queue, rather than blindly pulling messages at a fixed rate.

Feature: Add batchSize to enable multiple messages to be consumed at once

---

index.js
test/index.js

As a user of both sqs-consumer and sqs-producer I want a consistent way to interact with them. To facilitate this either the object needs exporting on sqs-producer or a .create function creating on the sqs-consumer which seems simpler and less intrusive.

Add .create function to match sqs-producer

---

README.md
index.js
package.json
test/index.js

As it is already specified on SQS instance creation like:
```js
// Init AWS credentials
AWS.config.update({
accessKeyId: process.env.AWS_ACCESS_KEY,
secretAccessKey: process.env.AWS_ACCESS_SECRET,
region: process.env.AWS_ACCESS_REGION
});
// Init SQS service
var sqs = new AWS.SQS();
...
```
and used as:
```js
var app = Consumer.create({
queueUrl: queues.smtp.QueueUrl,
sqs: sqs,
handleMessage: function (message, done) {
// do some work with `message`
done();
}
});
```

Make SQS Region config value optional. 

---

README.md
index.js
test/index.js

Continues from #39:
> I have a similar need as #15 as I'm running Node on AWS and ECS/Docker notifies a running container with a SIGTERM when it should be stopped. And as I'd like to handle this in a correct way, here is the proposal for it.

emit a stopped event when stopping the consumer

---

README.md
index.js
test/index.js

Add empty event. When all messages have been consumed emit 'empty' and continues with the poll.
Include:
- Updated tests
- Updated documentation
More info: [https://github.com/bbc/sqs-consumer/pull/49](url)

Add empty event

---

README.md
index.js
test/index.js

feat(event): add `message` parameter to message processing error events
Added the `message` which correlates to a processing error to the following events:
- _processMessage->error
- _processMessage->processing_error

add `message` to parameter set of error events during message processing

---

README.md

In the documentation in the README, the `handleMessageTimeout` parameter is incorrectly listed as being a `String` when in fact it should be a number.

Fix type of handleMessageTimeout parameter in README

---

README.md
src/consumer.ts
test/consumer.ts

Since `Consumer.stopped` is a private member of the Consumer, it is right now not possible to check if it's running or not from the outside.
In order to see from the outside if the polling has correctly started, I propose exposing the boolean through a getter `isRunning`.

feat: Expose Polling Status

---

package-lock.json
package.json
src/consumer.ts

Latest version of ts-jest will throw an error when an ES module uses require.
Issues: #159
Keeping to your linting style, that the import name has to be the same as the module name, the variable `debug` had to be renamed.

fix: 🐛 es modules can no longer use require

---

README.md

`handleMessageTimeout` is a `Number` and not a `String` 🙂

Fix incorrect type for `handleMessageTimeout` in readme

---

src/consumer.ts

Currently the function is called `terminateVisabilityTimeout` but the correct is `terminateVisibilityTimeout`.
A small spelling mistake.
In **README.md** it's already `terminateVisibilityTimeout`.

fix: terminateVisibilityTimeout function name

---

src/consumer.ts

Function name can't be updated because 'terminateVisibilityTimeout' is defined already as a private property.
Reverts bbc/sqs-consumer#209

Revert "fix: terminateVisibilityTimeout function name"

---

src/consumer.ts
src/index.ts

Export the `SQSMessage` type that comes from the AWS SDK.
When importing sqs-consumer in TypeScript code, it's useful to be able to create functions that are explicitly typed as receiving parameters of type `SQSMessage`. At the moment this requires importing the type directly from the aws-sdk, but my project has no other dependency on the aws-sdk. It would therefore be useful to be able to import it from the `sqs-consumer` package.
I do not think this change requires any new test cases.

feat: export SQS Message type

---

src/consumer.ts

This makes it easier to consume the events, because when you add an event handler, TypeScript already knows what event names are possible, and given the event name it knows what parameters the listener will be passed.
Add types for the events emitted by the `Consumer`. This means that TypeScript will error for event names that do not exist, and will know the types that are being passed to event listeners.
This improves code completions when using sqs-consumer. It also ensures more code is type safe.
It could break the build for TypeScript consumers, if they are using incorrect types in their code. It does not have any runtime impact, so is a non-breaking change for JavaScript consumers.
I don't believe this change needs any new tests, as it is only additional types.

feat: make the events strongly typed

---

README.md
src/consumer.ts
test/consumer.ts

This adds a new config property called `heartbeatInteval` that can be used in conjunction with `visibilityTimeout` to automatically extend the visibility timeout of a (batch of) message(s). Example behaviour with `visibilityTimeout=40` and `heartbeatInteval=30`:
- a message is retrieved from queue with visibility timeout set to 40 seconds that will take 75 seconds to process 
- after 30 seconds the visibility timeout is set to 70 seconds
- after 60 seconds the visibility timeout is set to 100 seconds
- after 75 seconds the processing completes and no further extensions are made to the visibility timeout for that message
Setting `heartbeatInteval` without also setting `visibilityTimeout` results in an error being thrown at startup. `heartbeatInteval >= visibilityTimeout` also results in an …

Automatically extend message visibility timeout

---

package.json
src/consumer.ts
test/consumer.ts

Basically, the code in `consumer.ts` in `processMessage` where it [calls changeVisabilityTimeout](https://github.com/bbc/sqs-consumer/blob/master/src/consumer.ts#L207) is incorrectly adding the `elapsedSeconds` onto the visibility timeout.
As the [AWS docs state](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html#changing-message-visibility-timeout) , the timeout being set takes effect starting at the time that the API call to `ChangeVisibilityTImeout` is made.
> For example, if the default timeout for a queue is 60 seconds, 15 seconds have elapsed since you received the message, and you send a ChangeMessageVisibility call with VisibilityTimeout set to 10 seconds, the 10 seconds begin to count from the time that you make the …

Issue #269 - fix the call to ChangeVisibilityTimeout to not include elapsed seconds

---

src/consumer.ts

Fix TypeError when handler throws not standard error.
The error can be from any type:
```
throw {};
throw 'a';
throw undefined;
```
Are valid
Currently, we try to set message property to the error value, which causes this error:
```
throw 'a';
....
....
{
"message":"TypeError: Cannot create property 'message' on string 'a'",
"stack":"TypeError: Cannot create property 'message' on string 'a'\n    at Consumer.executeHandler (/src/node_modules/sqs-consumer/dist/consumer.js:175:29)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
}
```
Fix an error as explained above.

Fix TypeError when handler throws not standard error.

---

README.md
src/consumer.ts
test/consumer.ts

New property to the package if the user doesn't want to delete the messages after consuming them
We have a use case where we 
- reading the message and starting k8s job
- pass the payload using environment variable to k8s job
- when the k8s job start running we want to delete the message

Option to not don't delete messages from sqs

---

README.md

Fix sentence mismatch message is also included in params and not error

Update README.md - Fix sentence mismatch message is also included in params and not error

---

src/consumer.ts
test/consumer.ts

- Added `await` to `changeMessageVisibility` and `changeMessageVisibilityBatchBatch` calls to SQS
- Convert error using `toSQSError` when catching visibility timeout errors
- Added unit tests
Fixes issue #275: visibility timeout changes are mostly used by the heartbeat (inside a Timer) that does not catch errors nor wait for the promise to be resolved. In those cases, it caused an unhandled exception/rejection.

Issue #275 - Fix visibility timeout error handler

---

README.md

Updates the status badge in the README to use GitHub Actions rather than Travis, now that we don't/can't use Travis

chore: updating the README build status badge

---

README.md

The default value for `waitTimeSeconds` was missing in the readme although other defaults were documented.
I wanted to know the default value and could not find it in the readme.
None of the above, as I only updated the readme.

Document default `waitTimeSeconds`

---

README.md

Moves the AWS iAM docs up in the README to below the Credentials section.
This makes it easier to find and is in a more logical order.

chore: moving aws iam docs to below credentials

---

src/consumer.ts
test/consumer.test.ts

Resolves #273
Adds the `NonExistentQueue` error code to the `isConnectionError` so that polling will be timed out if it occurs, like other connection errors
_A simple explanation of what the problem is and how this PR solves it_
- Extended the isConnectionError function to check if the error code is `AWS.SimpleQueueService.NonExistentQueue`
---
**Checklist:**

feat: add NonExistentQueue to isConnectionError

---

src/consumer.ts
src/index.ts
src/types.ts
test/consumer.test.ts

At the moment, we declare types within the same file as the main source code, and then export them individually, we should change this so that all types are declared in a single file and then exported at one.
**Changes:**
- Moved `ConsumerOptions` and `Events` from the `consumer` file to the `types` file
- Export everything from the types file automatically

chore: typescript enhancements

---

src/consumer.ts
src/errors.ts
src/timeout.ts
src/types.ts
src/validation.ts

A general clean up of the code to make it easier to work with.
- Moving all types to the types file
- Moving error functions to the errors file
- Moving validation functions to a validation file
- Moving timeout function to a timeout file

chore: cleaning up code

---

.github/workflows/docs.yml
.gitignore
.npmignore
.prettierignore
README.md
package-lock.json
package.json
src/consumer.ts
src/types.ts
typedoc.json

In this PR, we are using the package typedoc to automatically generate documentation from our TypeScript files, which will allow us to:
- Simplify the readme as currently everything has to go there and it can be hard to understand
- Remove the requirement to manually update the documentation, outside of adding comments to your code
- Adds more documentation within the code itself as this is how the docs are generated
- Creates a homepage for sqs-consumer, where we could provide more information about functionality in the future
- Added a workflow to automatically deploy the docs when deployed to main
- Added the dependency `typedoc` to generate the docs
- Added comments to the code to document the type definitions and functionality - basic
- Cleaned up the README (hopefully …

chore: using typedoc to auto generate docs

---

.github/workflows/coverage.yml
.github/workflows/test.yml
README.md
package-lock.json
package.json

Resolves #362
This PR removes support for Node v14 due to the removal of security support from April 30th, 2023
To support new functionality, such as the AbortController, we would need a polyfill to continue to support this version.
Alongside this, if the version is not supported by the Node.JS team, we cannot confidently support Node 14 for our users without further work.
- Changed the coverage CI to run from the LTS
- Remove v14 from the test CI matrix
- Added a note to the README to make it clear that we no longer support this version of Node
- Added a minimum engine version to the package.json so that this is clear (`16.19.0`)
---
**Checklist:**

chore: dropping node 14 support

---

test/config/cucumber.js
test/features/step_definitions/handleMessage.js
test/features/step_definitions/handleMessageBatch.js

Resolves NA
Made changes to the Cucumber config to fix how it responds to an error from SQS so that it is gracefully handled
When an error occurs in the E2E tests, the Consumer was not correctly stopped and so it was still listening for messages, this causes subsequent tests to fail as the previous run is handling messages instead of the new run.
Alongside this, Cucumber was not exiting after an error, which caused it to run indefinitely.
- Changed config to force Cucumber to exit
- Added `After` to the tests to stop the Consumer after a test has finished running
---
**Checklist:**

fix: gracefully handle errors in the e2e tests

---

README.md

Resolves #256
Updated the advice on message processing to make it clearer how to ensure messages are processed one at a time and that messages can be acknowledged.
It was previously unclear how this functionality works, updating the README makes this clearer.
- Updated the README
---
**Checklist:**

chore: updating advice on message processing

---

src/consumer.ts

Resolves #372
Fixed the options parameter of `consumer.stop` to be optional (in the code it was treated as an optional parameter - [here](https://github.com/bbc/sqs-consumer/blob/b2fd52735d67768047f65a8213cb8cd50844adc2/src/consumer.ts#L119)).
The option object is treated as required in the code but declared as required in the function's type.
* Changed the type of `options` to be optional.
---
**Checklist:**

fix: make the stop options optional

---

src/types.ts

As noted in this discussion:
https://github.com/bbc/sqs-consumer/discussions/377
We are not correctly documenting the default value for the region option, this PR resolves that by changing to documented value to `process.env.AWS_REGION || "eu-west-1"`

fix: correctly documenting region's default value

---

src/consumer.ts

Resolves #376
As described in the issue.
heartbeatTimeoutId was previously set globally, rather than within the processor function, which means that it errors when the Consumer is processing messages in parallel.
- Changed `heartbeatTimeoutId` to be set within the processing functions.
- Changed `handleMessageTimeoutId` to be set within the execute handler function

fix: timeout ids are not being set correctly for parallel running

---

README.md
package-lock.json

As discussed here:
https://github.com/bbc/sqs-consumer/discussions/382
We probably don't need to suggest always installing as a devDependency, while that is a use case, the most common use case is probably for it not to be.
This PR removes the dev flag from the README.

chore: removing dev from the install command

---

README.md
src/consumer.ts
src/types.ts
test/tests/consumer.test.ts

Resolves #370
As described in the feature request, this PR will add the ability for users to programatically update options for the Consumer. At the moment, this has only been configured with the ability to update `visibilityTimeout`, but in a way that'll be expandable in the future.
When an external factor occurs, users may want to trigger an update to the `visibilityTimeout` option that will take effect from that point on.
Rather than stopping and then restarting the Consumer, they would like to do this in the current instance.
- Added a new public method `.updateOption()`, this will take an option and a value and then update the provided option with the provided value
- Updated documentation around …

feat: adding the ability to update visibilityTimeout

---

README.md

Fixes the docs URL to updateOption (removes `/public`

fix: updateOption docs URL

---

src/consumer.ts
src/types.ts
test/tests/consumer.test.ts

Resolves #388
Fires a `started` event when the Consumer is started, like we do when it is stopped.
Allows implementations to extend functionality when the event is recieved
- Added the new event
- Emit the event on start

feat: emit a started event on consumer start

---

src/types.ts
test/tests/consumer.test.ts

Resolves #393
The `.once` event is not actually being fired only once due to the node API in the background being `.on` rather than `.once`
This changes the API that's used in the background for once to also be once
- Fixed the use of the background emitter for once
- Added a test for on and once event emitters

fix: once event is not only firing once

---

package-lock.json
src/consumer.ts
src/types.ts
src/validation.ts
test/tests/consumer.test.ts

Resolves #396
This extends the update api further by allowing our users to also update the batchSize and waitTimeSeconds programatically, like we allowed for visibilityTimeout previously.
This uses the same API as what we previously added, just adds more available options and methods for those options.

feat: extending the update api to update batchsize and waittimeseconds

---

package-lock.json
package.json
src/consumer.ts
src/emitter.ts
src/logger.ts
src/types.ts
test/tests/consumer.test.ts

Resolves #398, resolves #399
This PR extends the debuggers capabilities to both improve the logged messages but also add more debugging messages for when `.emit` is called and also a new message that sends while the user's handle message function is processing the message(s).
By adding these new methods, users will be able to better debug their applications and this primarily resolves issues where users are not listening to all events and also to allow users to determine if SQS Consumer is actually doing something during message processing, when it looks like it isn't.
- Created a new logger function that can be used across files
- Changed the messages that are sent in the debug logs to be simpler and …

feat: improving debugging capabilities

---

.github/workflows/test.yml

Part of https://github.com/bbc/sqs-consumer/issues/413 to set up testing against Node 20 before we move to support node 18 and 20 only.

chore(ci): start testing against node 20

---

src/consumer.ts
src/types.ts
test/tests/consumer.test.ts

Resolves #17 
This adds an option to hook your code just before and right after the SQS Client sends the `ReceiveMessageCommand`.
This is a change that is required if you'd like to use [OpenTelemetry](https://opentelemetry.io) in an organised way with their official js instrumentation for AWS SDK.
The way open telemetry works is that it creates `Traces` for what's going on in a distributed system. Think of them as a request or single SQS message processing. Those traces are then broken down into `Spans` later on for things like db communication, http request etc. Usually the top level span you'd want to create in a trace is one that is representing the consumer service. And that is where the problem kicks in. The way …

feat: add pre and post receive message callbacks

---

src/consumer.ts
src/controllers.ts
test/tests/consumer.test.ts

Resolves https://github.com/bbc/sqs-consumer/issues/389
This bug was originally closed, but I've been running into a related issue. Basically we want to start and stop a consumer based on a feature flag while using the `abort` option on `.stop`. The singleton `AbortController` makes it impossible to restart an aborted consumer, even if the consumer is recreated. This results in the abort signal persisting and being sent into any following AWS SDK calls.
This PR creates a new `AbortController` each time the consumer is started, which results in a fresh abort signal and allows the consumer to restart. I've also removed the previous `controller.ts` file as it's no longer used.
I've also added an associated test that fails without these changes that demonstrates how the abort …

Allow consumers stopped with abort: true to be restarted

---

package-lock.json
package.json
test/config/cucumber.js

- Updates all dependencies to the latest versions available.
- Removes old `publishQuiet` config from cucumber
- Replaces iPlayer eslint package with the new version (https://www.npmjs.com/package/eslint-config-iplayer)

chore: updating dependencies to the latest versions

---

package-lock.json
package.json

- Moving coverage testing from `nyc` to `c8`.
- Updated dependencies to the latest versions available.

chore: moving coverage testing to c8

---

README.md
src/types.ts
src/validation.ts
test/tests/consumer.test.ts

Adding ability to change pollingWaitTimeMs via `updateOption`.

Add pollingWaitTimeMs to UpdatableOptions

---

README.md

In response to #443, this updates the readme in an attempt to further clarify how acknowledgement and deletion of messages works.
It also restructures the documentation to ensure that the details are read in the correct order of operation.

chore: clarify how acknowledgement works

---

src/types.ts

Resolves #451
Previously, we listed a number of example values for the `attributeNames` name option, which did not entirely line up with the types that AWS was actually providing through `QueueAttributeName`.
To ensure that users aren't confused by the type provided by SQS Consumer.
- Removed the existing examples and replaced them with a link to: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-sqs/Variable/QueueAttributeName/

chore: updating `attributeNames` type docs

---

README.md
src/consumer.ts
src/types.ts
test/features/gracefulShutdown.feature
test/features/step_definitions/gracefulShutdown.js
test/features/utils/consumer/gracefulShutdown.js
test/tests/consumer.test.ts

Resolves https://github.com/bbc/sqs-consumer/discussions/410
Optionally delay the `emit('stopped')` event until in-flight messages
from the most recent poll have been processed.
Thank you for creating and maintaining a great module. `sqs-consumer` has been
pleasant tool to work with.
I'm entirely open to other suggestions of how to address the problem.  Maybe I'm missing something that already exists to accomplish this. Thanks in advance.
We are implementing a graceful shutdown of queue consumers just before issuing a process.exit() in our app
I'd like to support waiting for in-flight messages to be finalized before exiting, but it seems
the current implementation emits `stopped` without that guarantee.
**Code …

feat: Wait for msgs to be processed before emitting stopped

---

README.md
package.json
src/consumer.ts
test/features/step_definitions/gracefulShutdown.js
test/features/step_definitions/handleMessage.js
test/features/step_definitions/handleMessageBatch.js
test/tests/consumer.test.ts

Following on from #454, this removes the `isRunning` method in favour of a `status` method that returns both the running and polling state.
This would allow users to get the running and polling state from one method rather than creating multiple ways of getting this information, it can also be expanded in the future with more information.
This is a breaking change as it changes an existing method, outside of that, this change should not actually effect how the Consumer processes messages.
- Updated the README to document the old state and the removal of `isRunning`
- Added a new `getStatus` method to return the states
- Updated tests

feat!: replacing the isRunning method with status

---

src/consumer.ts
src/types.ts
test/tests/consumer.test.ts

Resolves #469
The PR removes the debugger that was previously added that would send a `handler_processing` debug log every second while polling was ongoing.
This is no longer required as the new status method returns this information.
This simplifies the codebase and makes it easier for us to maintain, and to understand.
- Removes the `handler_processing` debugger
- Changes `waiting_for_polling_to_complete` and `waiting_for_polling_to_complete_timeout_exceeded` to emit so users can react to them easier
- Fixes some flaky test issues
---

feat!: removing handler_processing debugger in favour of status

---

README.md

Resolves #464
Just adds a link to the readme to direct users to the documentation as we've had feedback that it wasn't easily found.

chore: adding a link to the documentation

---

src/consumer.ts
src/types.ts

Resolves #NUMBER
Add useQueueUrlAsEndpoint support in Consumer initialization
Let use QueueUrl hostname as the endpoint with [@aws-sdk/client-sqs@^v3.507.0](https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.507.0)
Add useQueueUrlAsEndpoint to ComsumerOptions, so it can be passed to SQSClient.
Add useQueueUrlAsEndpoint check in Consumer constructor to pass true as default value.
---
**Checklist:**

feat: Add useQueueUrlAsEndpoint to ConsumerOptions

---

src/errors.ts
test/tests/consumer.test.ts

Resolves #473
AWS surfaces a `CredentialsProviderError` when credentials could not be loaded from any providers, SQS Consumer doesn't currently handle this.
Handle error thrown by AWS SDK for JavaScript v3 which should be treated as an authentication failure.
- The `isConnectionError` function will return `true` when passed a `CredentialsProviderError`
---
**Checklist:**

fix: handle CredentialsProviderError from AWS SDK JS v3

---

.npmignore
.prettierrc.js
README.md
package-lock.json
package.json
scripts/addPackageJsons.js
src/bind.ts
src/consumer.ts
src/emitter.ts
src/errors.ts
src/index.ts
src/logger.ts
src/types.ts
src/validation.ts
test/config/cucumber.js
test/config/cucumber.mjs
test/features/step_definitions/gracefulShutdown.js
test/features/step_definitions/handleMessage.js
test/features/step_definitions/handleMessageBatch.js
test/features/utils/consumer/gracefulShutdown.js
test/features/utils/consumer/handleMessage.js
test/features/utils/consumer/handleMessageBatch.js
test/features/utils/delay.js
test/features/utils/producer.js
test/features/utils/sqs.js
test/tests/consumer.test.ts
tsconfig.cjs.json
tsconfig.esm.json
tsconfig.json

Resolves #467, #466
To support modern development, this package needs to transition from commonjs, this PR upgrades the codebase across the board to transition (builds will still output to esm and cjs).
It also upgrades a couple of dependencies that were blocked by still not being ESM, chai and p-event.
A discussion for this has been opened up here: https://github.com/bbc/sqs-consumer/discussions/477
In order to still be able to update dependencies while supporting and using modern development practices.
- Adds type module to the package.json
- Added a script to deploy package.json files for `type` to the two dist folders
- Removes main from package.json in favour of exports
- Sets the TypeScript lib …

feat!: transitioning to ESM

---

src/consumer.ts
src/errors.ts
test/tests/consumer.test.ts

Resolves #484
SQS Consumer does not currently handle some other connection / authentication errors that SQS sends out. This PR extends the code to handle these as connection errors, which will cause the polling timeout to be extended.
This allows users to better respond to these issues and stops the consumer from pinging SQS too often as these errors are expected to persist for some time.
- Extended isConnectionError to handle `InvalidAddress` | `InvalidSecurity` | `QueueDoesNotExist` | `RequestThrottled` | `OverLimit`
- Added the code to the debug logger so that the user can see why an authentication error occurred.

feat: extend authentication error to handle more codes

---

package.json

This adds the `main` and `types` fields back to hopefully support node versions 10 or older, this will be released as a canary for investigation.

chore: adding main and types back

---

.github/workflows/annotate-test-reports.yml
.github/workflows/coverage.yml
.github/workflows/pr-coverage.yml
.github/workflows/test.yml
package.json
test/config/cucumber.mjs

This removes the artefact upload from Ci as it's not super users.
Changes the workflows to use annotations for Cucumber and adds coverage annotations.
Investigating this at the moment, not really sure on the solution.

chore: enhance ci reports

---

src/consumer.ts
src/errors.ts
src/types.ts
test/tests/consumer.test.ts

Resolves #495
Adds the ability to set a new prop `extendedAWSErrors` is the options in order to extend the output of toSQSError with the response and metadata information from AWS.
This allows for better debugging, but also makes it controllable, by default the error response will be minimal and remain as it is today.
- Updated types to support response and metadata and align closer to AWS
- Added a new option, `extendedAWSErrors` to extend the error contents with both response and metadata.

feat: add the ability to extend errors from aws

---

package-lock.json
package.json

Resolves #509
This change ensures that users are downloading the new AWS SDK versions with the bug fixes for the memory leak issues.

chore: upgrading aws sdk to ^3.614.0

---

src/consumer.ts
src/types.ts
test/tests/consumer.test.ts

Resolves #515
This adds the ability to provide MessageSystemAttributeNames for SQS, it will be passed from options to SQS.
More information is available on the docs: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-sqs/Interface/ReceiveMessageCommandInput/
Because we didn't have it yet

feat: adding MessageSystemAttributeNames

---

README.md

Resolves #462
As aws sdk v2 is now in maintenance support rather than active support, we have decided to remove the note linking to the version of sqs-consumer that supported that version, this is due to us being unable to support packages not in an active state.

chore: removing aws sdk v2 note

---

src/consumer.ts
src/types.ts
test/tests/consumer.test.ts

Resolves #523
This allows users to introduce a delay before the message can be received again. In some cases this can improve the overall success rate.
When tasks are not time critical, a small delay can mitigate some intermittent errors, or give supervisors like K8s a little time to kill broken consumers.
- `terminateVisibilityTimeout` option has been updated to accept custom visibility timeouts.
I reused the option as I thought it was the most non-intrusive way to introduce this feature. If it appears to be confusing, I can also add a new option. But since the underlying SQS command is the same, I think it's ok.
---
**Checklist:**

feat: terminateVisibilityTimeout = number to customise the timeout

---

src/consumer.ts
src/errors.ts
test/tests/consumer.test.ts

This appends messageIds to the errors that are thrown by standard and timeout errors, this should make it easier to debug these errors.
This also appends the queueUrl to sqsErrors, alongside the messages if available.

feat: append more context to errors from the consumer 

---

src/consumer.ts
src/emitter.ts
src/types.ts
test/tests/consumer.test.ts

This automatically attaches the queueUrl to all emitted events.

feat: send the queueUrl alongside emitted events

---

src/consumer.ts
src/types.ts
test/features/events.feature
test/features/step_definitions/events.js
test/features/step_definitions/gracefulShutdown.js
test/tests/consumer.test.ts

Resolves #564
As described in the issue, https://github.com/bbc/sqs-consumer/pull/560 made a change that meant that all emitted events always included metadata as the last parameter, this meant that `message` was no longer the second parameter in error events which breaks some handling for users who where using that method to get the message details.
This ensures that the change is backwards compatible by making `emitError` emit undefined as the second parameter if messages were not provided to it.
NOTE: This does changed the type from setting `void` in the return union for the error emitted to event to be more explicitly `undefined`

fix: always emit a message from emitError

---

src/errors.ts
src/index.ts

Resolves #563
This exports the error classes SQSError, StandardError, TimeoutError which would enable users to create logic that uses them more easily, without having to recreate / maintain their own versions.

feat: export error classes

---

.github/workflows/annotate-test-reports.yml
.github/workflows/coverage.yml
.github/workflows/docs.yml
.github/workflows/pr-coverage.yml
.github/workflows/publish.yml
.github/workflows/test.yml
package-lock.json
package.json

As pre announced in the discussion here:
https://github.com/bbc/sqs-consumer/discussions/554
This PR changes our minimum level of Node support to version 20, it also updates some of our workflows to run on the LTS version, 22.

chore: setting minimum node version to 20

---

README.md
src/consumer.ts
src/types.ts
test/tests/consumer.test.ts

Resolves #582
> [!IMPORTANT]
> This is a **breaking** change as it changes the expectation of the library completely, we need to ensure users are aware of this and that the release version and change log reflects this.
This makes acknowledgment of messages easier understand as the system is no explicit by default.
If the user does not explicitly return a message or messages, nothing will be acknowledged if the alwaysAcknowledge setting is not on.
This PR also improves the documentation.
Users find the acknowledgement of messages confusing.
- Changes the code to not acknowledge if anything other than an object or an array is returned and the always acknowledge setting is not on.
- Improves the …

feat(breaking): do not acknowledge if void is returned

---

README.md
src/consumer.ts
src/types.ts
test/tests/consumer.test.ts

Resolves #596
Allowing void to be returned is problematic, we should have never supported it. It was implemented in the old codebase and never deprecated, this moves us on the path of deprecating the ability to return void by removing the option from the types and adding a log warning if void is ever used.
This will be released as a patch as it should have been part of the last major release (apologies), shortly after, a major will come out with a full deprecation.

chore: prepare for return void deprecation
