bbc/sqs-consumer

README.md
index.js
test/index.js

as in documentation https://aws.amazon.com/blogs/aws/simple-queue-service-message-attributes/ and http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SQS.html#receiveMessage-property

add message attributes

---

README.md
index.js
test/index.js

Just needed to override the VisibilityTimeout and waitTimeSeconds. :)

Added additional parameters visibilityTimeout and waitTimeSeconds

---

README.md
index.js
test/index.js

Attributte name option changed. Please check: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SQS.html
Thanks

Added 'AttributeNames' option

---

index.js
test/index.js

Stops the consumer when one of the possibe config errors is received. The possibe config errors are as follows:
- Missing credentials in config.
- The request signature we calculated does not match the signature you
provided.
- The security token included in the request is invalid.
Possibly could close #23.

Stops the consumer when there is a config error

---

package.json

Solves https://snyk.io/vuln/npm:qs:20140806-1

Upgraded codeclimate-test-reporter to 0.3.0

---

README.md

Appended the done() statement and the start functionality + error handling

README.md; Updated the example with AWS creds

---

index.js

This is a fix for https://github.com/bbc/sqs-consumer/issues/32.

 Make SQSError properly inherit from Error, and also have a stack trace

---

index.js

Using region environment var

---

CONTRIBUTING.md
README.md

* Add contributions guide to docs

Task: Add contributions

---

README.md
index.js
test/index.js

Option to terminate visibility timeout on error

---

index.js
test/index.js

Fix: Catch exceptions from handler and propagate err via callback.

---

package.json

Hi,
This PR upgrades aws-sdk to fix [this](https://github.com/aws/aws-sdk-js/issues/692#issuecomment-241825974) issue, which was merged into aws-sdk [here](https://github.com/aws/aws-sdk-js/pull/1114).
Tests still pass, and the issue seems to be resolved on my end.

Upgrading aws-sdk dependency

---

README.md
index.js
test/index.js

This is a more complete redo of PR #92.
Added a test, documentation, and fixed the linter complaint about double-quotes.

Emit 'response_processed' event once per batch

---

lib/consumer.js
test/consumer.js

Task: Add SQS Error properties.

---

src/consumer.ts
test/consumer.ts

WIP: Only await what is necessary to allow garbage collection

---

src/index.ts

This PR is a follow up from this issue: https://github.com/bbc/sqs-consumer/issues/150
I'm also exporting `ConsumerOptions` so any wrapper code around this library can make use of it.

Export ConsumerOptions

---

README.md
package-lock.json
package.json
src/consumer.ts
test/consumer.ts

Fixes tests and compiler issues from PR #129

Batch handler

---

src/consumer.ts

fix interface name typo

---

README.md

Adding http keepAlive note to documentation

Update README.md with http keepAlive note

---

package-lock.json
package.json

Updating dependency debug due to security hole.
Remove possible library vulnerabilities.

Bump debug from 4.1.1 to 4.3.1

---

README.md

The documented IAM actions miss some API calls.
Doc fix

Fix documented required IAM actions

---

README.md

Included https module on example. Used to reuse the same SQS instance.
It was not included in the example.

Included https module on example

---

package-lock.json
package.json

This PR updates the dependencies of sqs-consumer to the latest versions available.

chore(deps): updating dependencies

---

package-lock.json
package.json

chore(deps): updating dependencies - resolves GHSA-gpv5-7x3g-ghjv

---

.github/workflows/cla.yml
.github/workflows/coverage.yml
.github/workflows/dependency-review.yml
.github/workflows/docs.yml
.github/workflows/issues-to-projects.yml
.github/workflows/stale.yml
.github/workflows/test.yml

chore: updating workflow deps

---

.github/workflows/coverage.yml
.github/workflows/docs.yml
.github/workflows/test.yml

Adds tests for node 22 and changes the default node for workflows from 18 to 20.

chore: add node 22 tests

---

package-lock.json
package.json

feat: upgrading aws-sdk and debug

---

package-lock.json
package.json

Resolves #555
AWS SDK has made a type change which does not match the types in our build, this updates the SDK to the latest version available so we build with those types.

feat: updating aws sdk to 3.723.0
